import { Roboto } from "next/font/google";
import Footer from "../components/Footer";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"], // Pesos que você quer usar
  subsets: ["latin"],
  variable: "--font-roboto", // Variável CSS personalizada
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Conteúdo principal */}
        <main className="flex-grow">{children}</main>

        {/* Rodapé */}
        <Footer />
      </body>
    </html>
  );
}
